# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobile-test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mobile-test
 pod 'Alamofire', '~> 4.5'
  pod 'PromiseKit', '~> 4.4'
  pod 'PromiseKit/Alamofire', '~> 4.0'
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'ReachabilitySwift'
#  pod 'SwipeCellKit'
   pod 'SDWebImage', '~> 4.0'
  pod 'TagListView'
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod 'SCLAlertView'
  pod 'RealmSwift'
end



